display_xpath_res: "{{ display_xpath_res_override | default('false') }}"
display_directory_stats: "{{ display_directory_stats_override | default('false') }}"
tomcat_owner: "{{ tomcat_owner_override | default('tomcat_admin') }}"
tomcat_group: "{{ tomcat_group_override | default('tomcat') }}"
