---
tomcat_user: tomcat
tomcat_uid: 53
tomcat_group: tomcat
tomcat_gid: 53
tomcat_home: /opt/apache-tomcat-9.0.50/
# Red Hat JWS default home
#tomcat_home: /opt/jws-5.6/tomcat/
tomcat_catalina_logfile: logs/catalina.out
tomcat_service_name: tomcat

tomcat_listen_http_bind_address: 127.0.0.1
tomcat_listen_http_port: 8080

tomcat_listen_ajp_enabled: False
tomcat_listen_ajp_address: '::1'
tomcat_listen_ajp_port: '8009'

tomcat_native: False
