---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - zipfile is defined
      - zipfile_url is defined
      - zipfile_url | length > 0
      - path_to_zipfile is defined
    quiet: true

- name: "Check download archive path: {{ path_to_zipfile }}"
  ansible.builtin.stat:
    path: "{{ path_to_zipfile }}"
  register: archive_path

- name: Check local download archive path
  ansible.builtin.stat:
    path: "{{ lookup('env', 'PWD') }}"
  register: local_path
  delegate_to: localhost

- name: "Check downloaded archive {{ local_path.stat.path }}/{{ zipfile }}"
  ansible.builtin.stat:
    path: "{{ local_path.stat.path }}/{{ zipfile }}"
  register: local_archive_path
  delegate_to: localhost

- name: "Retrieve zipfile from RHN"
  block:

    - name: "Checking RHN credentials have been set before attemping to download archives."
      ansible.builtin.assert:
        that:
          - rhn_username is defined
          - rhn_password is defined
        quiet: True

    - name: "Install JWS with zipfile from RHN: {{ zipfile_url }}"
      redhat_csp_download:
        url: "{{ zipfile_url }}"
        dest: "{{ path_to_zipfile }}"
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
      delegate_to: localhost
  when:
    - not archive_path.stat.exists
    - not local_archive_path.stat.exists

- name: "Copy archives to target nodes: {{ jws_install_dir }}/{{ zipfile }}"
  ansible.builtin.copy:
    src: "{{ local_path.stat.path }}/{{ zipfile }}"
    dest: "{{ jws_install_dir }}/{{ zipfile }}"
    owner: "{{ jws.user }}"
    group: "{{ jws.group }}"
    mode: 0640
  when:
    - not archive_path.stat.exists
    - local_archive_path.stat is defined
    - local_archive_path.stat.exists
  become: yes
