---
- name: "Verify that provided checksum {{ patch_checksum }} matches with downloaded file."
  when:
    - patch_checksum is defined
    - patch_checksum | length > 0
  block:
    - name: "Load data on downloaded file: {{ jws_install_dir }}/{{ patch_bundle }}."
      ansible.builtin.stat:
        path: "{{ jws_install_dir }}/{{ patch_bundle }}"
      register: downloaded_file_metadata

    - name: "Verify that file checksum {{ downloaded_file_metadata.stat.checksum }} with provided one: {{ patch_checksum }}."
      ansible.builtin.assert:
        that:
          - downloaded_file_metadata is defined
          - downloaded_file_metadata.stat is defined
          - downloaded_file_metadata.stat.checksum is defined
          - downloaded_file_metadata.stat.checksum == patch_checksum
