- name: "Ensures required dependencies are installed"
  yum:
    name: "{{ item }}"
  loop:
    - perl-XML-XPath

- name: "Checks that root directories are appropriately defined."
  include_tasks: tasks/checks_root_dirs.yml
  loop:
    - { name: "CATALINA_HOME", path: "{{ tomcat.home }}", required: true }
    - { name: "CATALINA_BASE", path: "{{ tomcat.base }}", required: false }

- name: "Check that file's owner, group and mode are in compliance."
  include_tasks: tasks/checks_conf_files.yml
  loop:
    - { path: "{{ tomcat.home }}/{{ tomcat.conf.properties }}", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/{{ tomcat.conf.policy }}", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/{{ tomcat.conf.logging }}", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/conf/tomcat-users.xml", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/conf/jaspic-providers.xml", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/conf/server.xml", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/conf/web.xml", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/conf/context.xml", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0600" }
    - { path: "{{ tomcat.home }}/conf", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0750" }
    - { path: "{{ tomcat.home }}/temp", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0750" }
    - { path: "{{ tomcat.home }}/logs", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0750" }
    - { path: "{{ tomcat.home }}/webapps", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0750" }
    - { path: "{{ tomcat.home }}/bin", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0750" }

- name: "Checks server's configuration"
  include_tasks: tasks/execute_xpath_and_assess_result.yml
  loop:
    - { xpath: "//Connector[not(@allowTrace)or(@allowTrace='true')]", xmlfile: "{{ tomcat.home }}/conf/server.xml", error: "Connector SHOULD set allowTrace attribute to 'false'", success: "Trace settings are in compliance with Common Criteria recommendations" }
    - { xpath: "//Server[not(@port)or(port=8005)]", xmlfile: "{{ tomcat.home }}/conf/server.xml", error: "Shutdown port should be randomized", success: "Shutdown port has been randomized." }
    - { xpath: "//Connector[not(@SSLEnabled)or(@SSLEnabled=false)]", xmlfile: "{{ tomcat.home }}/conf/server.xml", error: "Connectors are not all using SSL", success: "Connectors are all using SSL" }
    - { xpath: "//Connector[not(@scheme)or(@scheme=http)]", xmlfile: "{{ tomcat.home }}/conf/server.xml", error: "The Connector scheme attribute SHOULD be defined and set to 'https'", success: "Connecter's schemes are in compliance with Common Criteria recommendatins." }
    - { xpath: "//Connector[not(@sslProtocol)or(@sslProtocol!='TLS')and(@SSLEnabled=true)]", xmlfile: "{{ tomcat.home }}/conf/server.xml", error: "If SSL protocols is enabled, associated attribute should be set to TLS'", success: "Connectors SSL protocol configuration are in compliance with Common Criteria recommendations." }
    - { xpath: "//security-constraint/user-data-constraint/transport-guarantee[text()!='CONFIDENTIAL']", xmlfile: "{{ tomcat.home }}/webapps/manager/WEB-INF/web.xml", error: "Manager webapp SHOULD only be accessed using SSL", success: "Manager webapp access has been properly configured to use SSL." }
    - { xpath: "//Connector[not(@xpoweredBy)or(@xpoweredBy=false)]", xmlfile: "{{ tomcat.home }}/conf/server.xml", error: "A used Connector has NOT the xpoweredBy attribute set to false", success: "No Connectors uses xpoweredBy" }
    - { xpath: "//Connector[not(@server)]", xmlfile: "{{ tomcat.home }}/conf/server.xml", error: "Connector needs to have the server attribute defined to remove default server header", success: "All Connectors have customized server header." }

- include_tasks: tasks/execute_xpath_and_assess_result.yml
  with_items:
    - { xpath: "//Listener[@className='org.apache.catalina.core.JreMemoryLeakPreventionListener']", xmlfile: "{{ tomcat.home }}/{{ tomcat.conf.server }}", not_empty_result: true, error: "TODO", success: "TODO" }

- name: "Check that CATALINA_BASE (if defined)."
  include_tasks: tasks/checks_conf_files.yml
  loop:
    - { path: "{{ tomcat.base }}", owner: "{{ tomcat_owner }}", group: "{{ tomcat_group }}", mode: "0750" }
  when: tomcat.base


- name: Find locate all context.xml files
  find:
    paths: "{{ tomcat.home }}"
    patterns: 'context.xml'
    file_type: file
    use_regex: yes
    recurse: yes
  register: matching_files

- name: "Checks server's configuration"
  include_tasks: tasks/process_context_xml.yml
  with_items:
    - "{{ matching_files.files }}"


- name: "Ensure removed apps are absent"
  include_tasks: tasks/remove_apps.yml
  loop:
    - "{{ tomcat.apps.to_remove }}"
  when: tomcat.apps.to_remove
