---
- name: Check that required parameters has been defined
  assert:
    that:
      - tomcat is defined
      - tomcat.install_method is defined
      - tomcat.install_method in tomcat.supported_install_method
    quiet: true
    fail_msg: "{{ tomcat.install_method }} does not exist or is not supported. Supported methods are: {{ tomcat.supported_install_method }}"

- name: "Stop and disable systemd service if running"
  include_tasks: systemd/disable.yml
  when:
    - tomcat_systemd_enabled is defined

- name: "Delete files from server home {{ tomcat.home }}"
  block:
    - name: "Check that server home has been provided"
      assert:
        that:
          - tomcat.home is defined
        quiet: true

    - name: "Deletes files from server home {{ tomcat.home }}"
      file:
        path: "{{ tomcat.home }}"
        state: absent
  when:
    - tomcat.install_method == 'zipfiles' or tomcat.install_method == 'local_zipfiles'
    - tomcat.install_method != 'rpm'

- block:
    - name: "Disable installed server to ensure package is removed"
      file:
        path: /opt/rh/jws5/enable
        state: absent

    - include_tasks: install/rpm.yml
      vars:
        dnf_command: 'groupremove'
  when:
    - tomcat.install_method == 'rpm'
