---
jws_setup: true
jws_java_version: 1.8.0
jws_listen_http_bind_address: 127.0.0.1
jws_systemd_enabled: True
jws_service_systemd_type: forking
jws_selinux_enabled: False
# workaround issue on Github actions
ansible_distribution: 'RedHat'
